[general]
import = [
  "~/.config/alacritty/colors.toml",
]

[window]
padding = { x = 10, y = 5 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 12.0

[cursor]
style = { shape = "Underline", blinking = "On" }
