[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
padding = { x = 6, y = 6 }
dynamic_padding = false
opacity = 0.8

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

size = 14

[cursor]
style = "Underline"
unfocused_hollow = false
